services:

  smtp:
    image: rnwood/smtp4dev:3.10.2
    ports:
      - 8280:80
      - 8225:25
    restart: no

  db:
    image: postgres:17.6-bookworm
    ports:
      - 5032:5432
    restart: no
    volumes:
      - ./data/pg/data:/var/lib/postgresql/data
      - ./data/pg/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./data/pg/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./data/ssl:/etc/postgresql/ssl:ro
    command: postgres
      -c ssl=on
      -c ssl_cert_file=/etc/postgresql/ssl/server.crt
      -c ssl_key_file=/etc/postgresql/ssl/server.key
      -c hba_file=/etc/postgresql/pg_hba.conf
      -c max_connections=200
    env_file:
      - ./data/pg/.env
    mem_limit: 2048m
    shm_size: 128mb

  api:
    image: mcr.microsoft.com/dotnet/aspnet:9.0.9-bookworm-slim
    ports:
      - 7003:7003
    restart: no
    working_dir: /app
    entrypoint: ["dotnet", "KanbanBoardApi.dll"]
    volumes:
      - ./KanbanBoardApi/publish:/app:ro
      - ./data/aspnet/DataProtectionKeys:/root/.aspnet/DataProtection-Keys
      - ./data/ssl:/ssl:ro
    env_file:
      - ./KanbanBoardApi/.env
    mem_limit: 1024m
    shm_size: 128mb
    depends_on:
      - db

  app:
    image: nginx:1.29.1-bookworm
    ports:
      - 80:80
      - 443:443
    restart: no
    volumes:
      - ./kanban-board-app/dist:/usr/share/nginx/html:ro
      - ./data/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/nginx/logs:/var/log/nginx/logs
      - ./data/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
