services:

  db:
    image: postgres:17.6-bookworm
    ports:
      - 127.0.0.1:5032:5432
    restart: no
    volumes:
      - ./data/pg/data:/var/lib/postgresql/data
      - ./data/pg/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./data/pg/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./data/ssl:/etc/postgresql/ssl:ro
    command: postgres
      -c ssl=on
      -c ssl_cert_file=/etc/postgresql/ssl/server.crt
      -c ssl_key_file=/etc/postgresql/ssl/server.key
      -c hba_file=/etc/postgresql/pg_hba.conf
      -c max_connections=200
    env_file:
      - ./data/pg/.env
    networks:
      default:
        aliases:
          - db.kanbanboard.net
    mem_limit: 2048m
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U robot -d kanban_board"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: mcr.microsoft.com/dotnet/aspnet:9.0.9-bookworm-slim
    ports:
      - 127.0.0.1:7003:7003
    restart: no
    working_dir: /app
    entrypoint: ["dotnet", "KanbanBoardApi.dll"]
    volumes:
      - ./KanbanBoardApi/publish:/app:ro
      - ./data/ssl:/ssl:ro
    env_file:
      - ./KanbanBoardApi/.env
    networks:
      default:
        aliases:
          - api.kanbanboard.net
    mem_limit: 1024m
    shm_size: 128mb
    depends_on:
      db:
        condition: service_healthy

  app:
    image: nginx:1.29.1-bookworm
    ports:
      - 80:80
      - 443:443
    restart: no
    volumes:
      - ./kanban-board-app/dist:/usr/share/nginx/html:ro
      - ./data/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/nginx/logs:/var/log/nginx/logs
      - ./data/ssl:/etc/nginx/ssl:ro
    networks:
      default:
        aliases:
          - kanbanboard.net
          - www.kanbanboard.net
    depends_on:
      api:
        condition: service_started

  mail:
    image: rnwood/smtp4dev:3.10.3
    ports:
      - 127.0.0.1:8180:80
      - 127.0.0.1:8125:25
      - 127.0.0.1:8143:143
    restart: no
    volumes:
      - ./data/mail/data:/smtp4dev
      - ./data/mail/DataProtectionKeys:/root/.aspnet/DataProtection-Keys
      - ./data/ssl:/ssl:ro
    environment:
      - ServerOptions__TlsMode=ImplicitTls
      - ServerOptions__TlsCertificate=/ssl/server.crt
      - ServerOptions__TlsCertificatePrivateKey=/ssl/server.key
      - ServerOptions__SecureConnectionRequired=true
    networks:
      default:
        aliases:
          - mail.kanbanboard.net
