START TRANSACTION;
CREATE TABLE kanban_tasks (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    title character varying(100) NOT NULL,
    description character varying(2000) NOT NULL,
    priority double precision NOT NULL,
    status integer NOT NULL,
    assigned_user_id integer,
    assigned_at timestamp with time zone,
    created_by_user_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_by_user_id integer,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_kanban_tasks PRIMARY KEY (id),
    CONSTRAINT fk_kanban_tasks_users_assigned_user_id FOREIGN KEY (assigned_user_id) REFERENCES users (id) ON DELETE NO ACTION,
    CONSTRAINT fk_kanban_tasks_users_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE NO ACTION,
    CONSTRAINT fk_kanban_tasks_users_updated_by_user_id FOREIGN KEY (updated_by_user_id) REFERENCES users (id) ON DELETE NO ACTION
);

CREATE INDEX ix_kanban_tasks_assigned_user_id ON kanban_tasks (assigned_user_id);

CREATE INDEX ix_kanban_tasks_created_by_user_id ON kanban_tasks (created_by_user_id);

CREATE INDEX ix_kanban_tasks_updated_by_user_id ON kanban_tasks (updated_by_user_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250922192817_Add_KanbanTasks_Table', '9.0.9');

COMMIT;

