START TRANSACTION;
CREATE TABLE data_protection_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    friendly_name text,
    xml text,
    CONSTRAINT pk_data_protection_keys PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250926081706_Add_DataProtectionKeys_Table', '9.0.9');

COMMIT;

