START TRANSACTION;
DROP TABLE role_claims;

DROP TABLE user_roles;

DROP TABLE roles;

CREATE TABLE user_agents (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_agent_hash character varying(64) NOT NULL,
    user_agent_string text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_user_agents PRIMARY KEY (id)
);

CREATE TABLE user_sessions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    user_agent_id integer,
    login_date timestamp with time zone NOT NULL,
    session_expiry_date timestamp with time zone,
    refresh_token_id character varying(64) NOT NULL,
    access_token_id character varying(64) NOT NULL,
    refresh_token_issue_date timestamp with time zone NOT NULL,
    access_token_issue_date timestamp with time zone NOT NULL,
    requests integer,
    last_request_date timestamp with time zone,
    CONSTRAINT pk_user_sessions PRIMARY KEY (id),
    CONSTRAINT fk_user_sessions_user_agents_user_agent_id FOREIGN KEY (user_agent_id) REFERENCES user_agents (id),
    CONSTRAINT fk_user_sessions_users_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE UNIQUE INDEX ix_user_agents_user_agent_hash ON user_agents (user_agent_hash);

CREATE INDEX ix_user_sessions_user_agent_id ON user_sessions (user_agent_id);

CREATE INDEX ix_user_sessions_user_id ON user_sessions (user_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260131132523_Change_Identity_Tables_And_Add_UserAgents_And_UserSessions_Tables', '10.0.2');

COMMIT;

